# Generated by Django 3.2 on 2021-07-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shawrma',
            new_name='Pizza',
        ),
    ]
