# Generated by Django 3.2 on 2021-07-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_rename_shawrma_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biriyani',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='biriyani',
            name='price',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='biriyani',
            name='rating',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='burger',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='burger',
            name='price',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='burger',
            name='rating',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='rating',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='rating',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='price',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='rating',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
